# success
RES_CODE_SUCCESS = "E200"
RES_CODE_MIS1006 = "MIS10006"
DATA_FETCH_SUCCESSFULLY = "FETCHED SUCCESSFULLY"

# exception handler
RES_CODE_FAILURE = "E400"
OPERATION_FAILED_GENERIC_MESSAGE = "OPERATION FAILED"
RES_CODE_OFG001 = "OFG001"
OPERATION_FAILED_GENERIC_MESSAGE = "OPERATION FAILED"